### ISSUE TITLE
rosunit fails to generate XML for a unit test that throws an exception

### ISSUE THREAD

**Issue by pjreed** [ros/ros#114]
For example, an easy way to test this is to make a C++ unit test that intentionally causes a segmentation fault and does not catch it.

The output from such a test looks like so:

```
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/preed/src/test/src/test_project --package=test_project --results-filename test_test_project_test.xml --results-base-dir /home/preed/src/test/build/test_project/test_results /home/preed/src/test/src/test_project/test/test_project_test.test 
... logging to /home/preed/.ros/log/rostest-regulus-113281.log
[ROSUNIT] Outputting test results to /home/preed/src/test/build/test_project/test_results/test_project/rostest-test_test_project_test.xml
Traceback (most recent call last):
  File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 171, in rostestmain
    result = xml_runner.run(suite)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 263, in run
    result.print_report(stream, time_taken, out_s, err_s)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 190, in print_report
    stream.write(ET.tostring(self.xml(time_taken, out, err).getroot(), encoding='utf-8', method='xml'))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 176, in xml
    test_suite.append(info.xml())
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 70, in xml
    self._print_error(testcase, 'failure', self._failure)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 102, in _print_error
    error.set('type', str(error[0].__name__))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 266, in __getitem__
    return self._children[index]
IndexError: list index out of range
-- run_tests.py: verify result "/home/preed/src/test/build/test_project/test_results/test_project/rostest-test_test_project_test.xml"
Invalid XML in result file '/home/preed/src/test/build/test_project/test_resultstest_project/rostest-test_test_project_test.xml' (even after trying to tidy it): no element found: line 2, column 0 
make[3]: Leaving directory `/home/preed/src/test/build/test_project'
```

There are two problems in the `_TestInfo._print_error` method.  The first is that it creates a local variable named "error" that hides the "error" argument passed into it, so attempts to access the argument are actually accessing the local variable instead.  The second is that it tries to call a method named "error.text", but error.text is actually a value that should be assigned.

I've got a fix for this but am having a little difficulty figuring out how to make a unit test that reasonably demonstrates the problem, since I observed it by having a separate, standalone C++ test that was segfaulting...

**Comment by dirk-thomas** [comment]
Thank you for pointing it out. The regression has already been fixed on the kinetic-devel branch: b40a0b775e44513d1b092dbe741f548d3ee9b185

I just cherry-picked the fix to the jade-devel branch: 706af303ec8e82f4d05b87236b651e9b66de7637
