### ISSUE TITLE
Unknown error initiating TCP/IP socket error ros-kinetic with px4

### ISSUE THREAD

**Issue by ashirsat** [ros/ros#246]
Hi,

I am trying to run the px4 SITL with ros-kinetic on ubuntu 16.04.

I know that ros-kinetic is end of life and so is Ubuntu 16.04 But i think this issue is with base ros package. Hence I am posting this.

I get this error when I try to roslaunch px4 mavros_posix_sitl.launch file.
PX4 firmware branch is tags/v1.8.0 

The error reported is

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

Please let me know if there is a workable solution since I am stuck with ros kinetic for a project.

Any help is appreciated.

Thanks,
Aniket

**Comment by dirk-thomas** [comment]
> I know that ros-kinetic is end of life and so is Ubuntu 16.04

That is incorrect. Both are supported until April 2021.

Please provide complete steps to reproduce the problem if you would like others to help you debug your problem.
